# Generated by Django 5.2 on 2025-05-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='notebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Notebooks.notebook'),
        ),
    ]
