# Generated by Django 5.2 on 2025-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebooks', '0002_alter_page_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='index',
            field=models.CharField(blank=True, verbose_name=20),
        ),
        migrations.AddField(
            model_name='page',
            name='transcription',
            field=models.TextField(blank=True),
        ),
    ]
