# Generated by Django 5.2 on 2025-05-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notebooks', '0003_page_index_page_transcription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Scan',
        ),
    ]
