# Generated by Django 5.2 on 2025-05-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notebooks', '0004_rename_page_scan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='name',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='index',
            new_name='seq_num',
        ),
    ]
