# Generated by Django 5.2 on 2025-05-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebooks', '0005_rename_name_scan_file_rename_index_scan_seq_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
